name: Java CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Compile
      run: mvn compile

    - name: Test
      run: mvn test

    - name: Build
      run: mvn package

    - name: Deploy
      run: |
        scp /path/to/your/target/HelloWorld.war ubuntu@172.31.34.150:/opt/tomcat/webapps/testapp.war
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

